### ISSUE TITLE
cheffiles.pivotallabs.com is dead

### ISSUE THREAD

**Issue by pivotal-rivals** [pivotal-sprout/sprout-terminal#1]
The update_font recipe references cheffiles.pivotallabs.com which seems to be dead. Not sure what to replace it with; @hiremaga?

[recipes/update_font.rb](https://github.com/pivotal-sprout/sprout-terminal/blob/master/recipes/update_font.rb)

```
remote_file font_path do
  source term_opts['font_src']
  owner node['sprout']['user']
end
```

[attributes/default.rb](https://github.com/pivotal-sprout/sprout-terminal/blob/master/attributes/default.rb#L2)

```
node.default['sprout']['terminal']['font_src'] = 'http://cheffiles.pivotallabs.com/MenloRegular18pt.bin'
```

**Comment by bonzofenix** [comment]
Same here

**Comment by bonzofenix** [comment]
Here is a workaround @pivotal-rivals: 

```
$ vim Cheffile # change pivotal-sprout/sprout-terminal for bonzofenix/sprout-terminal
$ gem install librarian-chef
$ librarian-chef update
$ bundle exec soloist
```

see https://github.com/bonzofenix/sprout-terminal/commit/20d2822cba4064a57da0d0ff3bab37810bc3809b

**Comment by hiremaga** [comment]
Thanks @pivotal-rivals We've [removed](d4fea8974b5f7b4b95d10971a899fce636ebd14e) the affected recipe for now.
